import type { PluginRegistry } from "./registry.js";

export function createEmptyPluginRegistry(): PluginRegistry {
  return {
    plugins: [],
    tools: [],
    hooks: [],
    typedHooks: [],
    channels: [],
    channelSetups: [],
    providers: [],
    speechProviders: [],
    mediaUnderstandingProviders: [],
    imageGenerationProviders: [],
    videoGenerationProviders: [],
    musicGenerationProviders: [],
    memoryEmbeddingProviders: [],
    realtimeTranscriptionProviders: [],
    webSearchProviders: [],
    cliBackends: [],
    agentHarnesses: [],
    skillProviders: [],
    researchProviders: [],
    osAutomationProviders: [],
    voiceInterfaceProviders: [],
    autoCoderProviders: [],
    dealSourcingProviders: [],
    leadGenerationProviders: [],
    salesAutomationProviders: [],
    growthHackingProviders: [],
    saasBuilderProviders: [],
    revenueOptimizationProviders: [],
    contentFactoryProviders: [],
    projectManagerProviders: [],
    decisionEngineProviders: [],
    businessLoopProviders: [],
    gatewayHandlers: {},
    httpRoutes: [],
    cliRegistrars: [],
    services: [],
    commands: [],
    conversationBindingResolvedHandlers: [],
    diagnostics: [],
  };
}
